import mongoose from "mongoose";

const { Schema, models, model } = mongoose;

const bidSchema = new Schema(
  {
    auction: { type: Schema.Types.ObjectId, ref: "Auction", required: true, index: true },
    bidder: { type: Schema.Types.ObjectId, ref: "User", required: true, index: true },
    amount: { type: Number, required: true, min: 0 },

    // Auto-bid: the system bids up to maxAutoBid on the bidder's behalf.
    isAutoBid: { type: Boolean, default: false },
    maxAutoBid: { type: Number, default: 0 },

    // proxy = generated by the auto-bid engine; manual = user clicked bid.
    type: { type: String, enum: ["manual", "proxy"], default: "manual" },
    status: { type: String, enum: ["active", "outbid", "won", "lost"], default: "active", index: true },
  },
  { timestamps: true }
);

bidSchema.index({ auction: 1, amount: -1 });
bidSchema.index({ auction: 1, bidder: 1 });

export default models.Bid || model("Bid", bidSchema);
